version: '2'
services:
    portal-cassandra-migration:
        environment:
            - CASSANDRA_CONTACT_POINT=portal-cassandra
            - USER=docker-cassandra-migration
            # - DEBUG_LOG=1 # uncomment to show debug logs during the migration process
        build:
            context: .
            dockerfile: cassandra/Cassandra-Migration.Dockerfile
        volumes:
            - ../resources/config/cql:/cql:ro
