version: '2'
services:
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    jhipster-elasticsearch:
        build: jhipster-elasticsearch/
        ports:
            - "9200:9200"
#        environment:
#            - http.host=0.0.0.0
#            - transport.host=127.0.0.1
        # Uncomment this section to have elasticsearch data loaded from a volume
        #volumes:
        #   - ./log-data:/usr/share/elasticsearch/data
    jhipster-logstash:
        build: jhipster-logstash/
        environment:
            - INPUT_TCP_PORT=5000
            - INPUT_UDP_PORT=5000
            - ELASTICSEARCH_HOST=jhipster-elasticsearch
            - ELASTICSEARCH_PORT=9200
            - LOGSTASH_DEBUG=true
        ports:
            - "5000:5000"
            - "9600:9600"
        depends_on:
            - jhipster-elasticsearch

    jhipster-console:
        build: jhipster-console/
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
        ports:
            - "5601:5601"
        depends_on:
            - jhipster-elasticsearch

    jhipster-import-dashboards:
        build: jhipster-import-dashboards/
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
        depends_on:
            - jhipster-elasticsearch

    # jhipster-alerter:
    #     build: jhipster-alerter/
    #     # Uncomment this section to enable alerting
    #     volumes:
    #         #- ./alerts/config.yaml:/opt/elastalert/config.yaml
    #         - ./alerts/rules/:/opt/elastalert/rules

    #https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configuration.html
    # jhipster-curator:
    #      build: jhipster-curator/
    #      environment:
    #          - ES_HOST=jhipster-elasticsearch
    #          - UNIT_COUNT=7
    #          - UNIT=days

    # jhipster-zipkin:
    #     build: jhipster-zipkin/
    #     environment:
    #         - ES_HOSTS=http://jhipster-elasticsearch:9200
    #         - ZIPKIN_UI_LOGS_URL=http://localhost:5601/app/kibana#/dashboard/logs-dashboard?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1h,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:1,id:logs-levels,panelIndex:2,row:1,size_x:6,size_y:3,type:visualization),(col:7,columns:!(stack_trace),id:Stacktraces,panelIndex:7,row:1,size_x:4,size_y:3,sort:!('@timestamp',desc),type:search),(col:11,id:Log-forwarding-instructions,panelIndex:8,row:1,size_x:2,size_y:3,type:visualization),(col:1,columns:!(app_name,message),id:All-logs,panelIndex:9,row:4,size_x:12,size_y:7,sort:!('@timestamp',asc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'{traceId}')),title:logs-dashboard,uiState:())
    #     ports:
    #         - 9411:9411